ZcashFoundation/frost-tools

- .gitignore
- Makefile.toml
- README.md
Adds content to README
Creates Makefile commands
This closes [#339](https://github.com/ZcashFoundation/frost/issues/339)
> Add details to README (#339)

- Cargo.lock
- coordinator/src/step_2.rs
- coordinator/src/step_3.rs
- coordinator/src/tests/steps.rs
- participant/Cargo.toml
- participant/src/cli.rs
- participant/src/round1.rs
- participant/src/round2.rs
- participant/src/tests/cli.rs
- participant/src/tests/round1.rs
- participant/src/tests/round2.rs
- participant/tests/integration_tests.rs
- trusted-dealer/Cargo.toml
- trusted-dealer/src/output.rs
- trusted-dealer/src/tests/output_tests.rs
A lot of tests will need to be fixed. I started doing that but realized it would take a bit of work, so I just commented them out and we'll fix them later. Sorry for the mess!
I also improved some of the prompts to make them clearer.
In the participant demo, I also changed the first part to be able to read either a SecretShare or a KeyPackage (rather than just SecretShare). The reason is that DKG produces KeyPackages directly.
> Use serde for all demos

- .github/workflows/main.yml
- Cargo.lock
- coordinator/Cargo.toml
- coordinator/src/cli.rs
- coordinator/src/step_1.rs
- coordinator/src/step_2.rs
- coordinator/src/step_3.rs
- dkg/Cargo.toml
- dkg/src/cli.rs
- dkg/src/inputs.rs
- participant/Cargo.toml
- participant/src/cli.rs
- participant/src/round1.rs
- participant/src/round2.rs
- trusted-dealer/Cargo.toml
- trusted-dealer/src/cli.rs
- trusted-dealer/src/inputs.rs
- trusted-dealer/src/output.rs
- trusted-dealer/src/trusted_dealer_keygen.rs
Depends on #62 
This adds support for RedPallas using the `redpallas` feature (e.g. `cargo run --bin dkg --features redpallas`)
[Features should be additive](https://doc.rust-lang.org/cargo/reference/features.html#feature-unification) and this goes against that, but since we have only binaries and not libraries, it seems fine.
When  `redpallas` is activate, support for rerandomized FROST is also enabled. Currently the randomizer is always read (even though ideally it should be generated by the coordinator) because this is currently required by the demo.
> add support for redpallas

- .github/workflows/main.yml
- Cargo.lock
- Cargo.toml
- coordinator/Cargo.toml
- dkg/Cargo.toml
- participant/Cargo.toml
- participant/src/round2.rs
- tests/Cargo.toml
- trusted-dealer/Cargo.toml
- trusted-dealer/src/inputs.rs
- Fix compiling issues with redpallas feature
- Update reddsa to point to main (later we can make a new reddsa release after frost 1.0.0-rc.0 is released, and point to that)
- Add redpallas build to CI to make sure it doesn't get broken again
> Fix redpallas issues

- rust-toolchain.toml
Forgot to add it before. Automatically uses nightly when using `cargo`.
> add rust-toolchain.toml

- participant/src/cli.rs
The group signature must be a quoted string, to meet serde_json formatting needs, which is not clear to the user currently.
> Improve messaging during dkg demo

- coordinator/src/args.rs
- coordinator/src/cli.rs
- coordinator/src/comms.rs
- coordinator/src/comms/socket.rs
- coordinator/src/main.rs
- coordinator/src/step_1.rs
- coordinator/src/step_2.rs
- coordinator/src/step_3.rs
- participant/src/args.rs
- participant/src/comms.rs
- participant/src/comms/cli.rs
- participant/src/comms/socket.rs
- participant/src/main.rs
- participant/src/round2.rs
Depends on #138 .
I also changed a bit the semantic of the `cli` flag. After thinking about it, I think it makes more sense for it to control only whether to use sockets comms or CLI "comms" and not how inputs to the program are read. So now it should be possible to e.g. read the message from the CLI even if socket comms are used, if the user wishes to.
> Phase 1: also send randomizer

- server/src/functions.rs
- server/src/lib.rs
- server/src/state.rs
- server/src/types.rs
- server/tests/integration_tests.rs
> Phase 2: add multi-message support to server

- Cargo.lock
- server/Cargo.toml
- server/src/functions.rs
- server/src/lib.rs
- server/src/main.rs
- server/src/state.rs
- server/src/types.rs
Based on #147 
To use it, prefix commands with `RUST_LOG=debug` e.g. `RUST_LOG=debug cargo run...`
> Phase 2: add server logging

- Cargo.lock
- dkg/src/cli.rs
- dkg/tests/integration_tests.rs
- trusted-dealer/Cargo.toml
- trusted-dealer/src/cli.rs
RedPallas keys need to be converted to ensure they have a even-Y public key. This is done automatically if you use the `reddsa` non-generic APIs, which we were doing before. But now that our code is generic after #244, this must be done manually.
> convert redpallas keys into even-Y format

- Cargo.lock
- coordinator/Cargo.toml
- coordinator/src/args.rs
- coordinator/src/comms/http.rs
- frost-client/Cargo.toml
- frost-client/src/args.rs
- frost-client/src/coordinator.rs
- frost-client/src/participant.rs
- frost-client/src/trusted_dealer.rs
- participant/Cargo.toml
- participant/src/args.rs
- participant/src/comms/http.rs
- server/tests/integration_tests.rs
Based on #328 
Closes #179 
With this, we finally have encryption/authentication!
My strategy was to change the ProcessedArgs struct to allow specifying some additional stuff that is only required for this. That way, the old tools keep working the same as they did before (we can decided later if we want them gone or not...). I refactored the participant and coordinator main functions so that they could be called as a library, being passed a ProcessedArgs as input.
I created a `Noise` struct (arbitrarily in the `participant` crate, which is then also imported by `coordinator`) to abstract an annoyance of the `snow` crate, which is that while it supports sending/receiving a message along with the handshake, it requires explicitly marking the handshake as finished.
This also updates the …
> frost-client: add encryption and authentication

- Cargo.lock
- server/Cargo.toml
- server/src/functions.rs
- server/src/state.rs
Based on #383 
Closes #375 
This adds sessions timeouts, and fixes the existing timeouts which weren't being enforced.
I tested this manually; change the session or access token to e.g. 10 seconds, start the server, start a coordinator and wait. It will eventually error out due to the session or access token timing out.
We can add a proper test later on.
> server: add sessions timeouts

- Cargo.lock
- server/Cargo.toml
- server/src/functions.rs
- server/src/lib.rs
- server/src/types.rs
- server/src/user.rs
- server/tests/integration_tests.rs
Based on #375 
Closes #374 
This basically turns `AppError` into an enum, and changes previous uses of it to use specific values.
A new public `Error` was introduced which is effectively the JSON value returned on error, and it's what client will interact with. The `AppError` is converted into `Error` in its `IntoResponse` implementation, which is used by axum when converting `AppError` into a response.
Since clients will only see the `code` and `msg` fields, I added a `const` for each error enum. We might want to allow converting an `Error` back to an `AppError` for Rust clients, but I don't think we need to worry about that for now.
> server: improve error handling

- frost-client/src/args.rs
- frost-client/src/config.rs
- frost-client/src/trusted_dealer.rs
Closes #378
This breaks compatibility with older configs.
I kept the group selection via public key - I think that's easier to specify than the group description; so the user will need to run `frost-client groups`, copy the public key, and use that for the other commands. I think that's acceptable for this tool, but suggestions are welcome.
> frost-client: add support for group description

- Cargo.lock
- frost-client/Cargo.toml
- frost-client/src/args.rs
- frost-client/src/config.rs
- frost-client/src/main.rs
- frost-client/src/participant.rs
- frost-client/src/session.rs
- participant/src/comms/http.rs
Based on #179 
Closes #376 
Allows listing sessions, and specifying which session to use.
Choosing which session to use can be still confusing if e.g. there are multiple sessions with the same coordinator and participants. At the end of the day what truly matters is the message being signed, and that is only sent in round 2. I think we can ignore this for now (I don't think people will have dozens of concurrent FROST signing sessions) but we might want to revisit this issue later.
> frost-client: support multiple sessions

- coordinator/src/args.rs
- coordinator/src/comms/http.rs
- frost-client/src/session.rs
- participant/src/args.rs
- participant/src/comms/http.rs
- server/Cargo.toml
- server/README.md
- server/src/functions.rs
- server/src/lib.rs
- server/src/main.rs
- server/src/state.rs
- server/src/types.rs
- server/tests/integration_tests.rs
Based on #307 
This improves some stuff I noticed while working on https://github.com/ZcashFoundation/frost/pull/811
- Change default port of clients to 443 (this will mismatch with the server default 2744 on purpose; the user is supposed to deploy nginx on 443 and redirect to 2744, or do their own thing by specifying the ports using the flags)
- Use `PublicKey` for other instances of public key in arguments, to make sure they're serialized as hex strings and not as arrays of numbers
- Remove `num_signers` from session handling, it's not really needed
- Make the server logs in INFO level by default (before it wouldn't log anything unless RUST_LOG variable was set)
- Change tracing logs to DEBUG instead of INFO
- Renamed `uuid` argument to `challenge`
> server: misc cleanups

- Cargo.lock
- coordinator/Cargo.toml
- coordinator/src/args.rs
- coordinator/src/comms/http.rs
- frost-client/src/config.rs
- frost-client/src/coordinator.rs
- frostd/src/types.rs
- frostd/tests/integration_tests.rs
- participant/src/comms/http.rs
Based on #423 
Closes #429 
Before authentication we were sending identifiers between coordinator and participants to identify peers, but that's insecure; we forgot to change it after we added authentication.
This changes the coordinator and participant to not send identifiers along with messages.
> coordinator, participant: don't send identifier; get it from channel authentication

- zcash-sign/Cargo.toml
- zcash-sign/src/main.rs
While the path is `zcash-sign` the name was still `frost-zcash-sign`. This changes that; I did this because I'm updating the demo instructions and I'm changing to instruct the user to `cargo install` instead of `cargo run`-ing all the time, and in that case the name of the binary will matter.
> zcash-sign: fix name of binary

- Cargo.lock
- Cargo.toml
- zcash-sign/Cargo.toml
- zcash-sign/src/args.rs
- zcash-sign/src/sign.rs
Based on #437 
This fixes our signing tool which stopped working post-NU6.
This also fixes the issue that prevented `zcash-sign` being part of the workspace, so I now moved it back to the workspace.
> zcash-sign: update with recent ECC crates

- frost-client/src/coordinator.rs
- frost-client/src/participant.rs
`--server-url localhost:443` would wrongly use port `2744`.
The reason is that  `Url::port()` weirdly returns `None` even if port `443` is explicitly specified. This PR fixes that by switching to `port_or_known_default()`.
Note that per its docs `port_or_known_default()` always returns `Some(x)` if the protocol is known, which we know it is since we prepend `https://` to the user specified host before calling `parse()`.
This also ends up turning `443` into the default which is probably the right thing for regular usage.
> frost-client: fix port handling

- dkg/src/cli.rs
- dkg/src/comms.rs
- dkg/src/comms/cli.rs
- dkg/src/comms/http.rs
`max_signers` was hard-coded to zero in `CLIComms`. This resulted in failure when running CLI DKG demo.
Also method `get_identifier` is renamed into `get_identifier_and_max_signers` to reflect better what it does
> Fix max_signers retrieval in CLIComms

- Cargo.lock
- frostd/Cargo.toml
- frostd/src/user.rs
https://github.com/ZcashFoundation/frost-zcash-demo/pull/419 failed because it required updating all axum crates, and there were also some breaking changes. This updates them all and makes the necessary adjustments.
> frostd: update axum crates

- coordinator/src/cli.rs
- coordinator/src/comms/http.rs
- coordinator/src/step_1.rs
- coordinator/src/step_2.rs
- coordinator/src/step_3.rs
- coordinator/src/tests/steps.rs
- dkg/src/comms/http.rs
- frost-client/src/args.rs
- frost-client/src/dkg.rs
- frost-client/src/session.rs
- frostd/src/functions.rs
- participant/src/cli.rs
- participant/src/comms/http.rs
- participant/src/round2.rs
- participant/src/tests/round2.rs
- Add a prompt that shows the message before signing and asks for consent to proceed;
- Clean up prints in general
- Add a flag to allow closing all existing sessions
- Fix a bug in the server that would prevent listing sessions where you are the coordinator but not a signer
> frost-client, frostd: show message to gather consent; overall printing clean up; fix sessions

- frost-client/src/contact.rs
Closes #474 
I also added a check for duplicated pubkeys. Since we remove by pubkey, having two contacts with the same pubkey would lead to ambiguity, and it doesn't make sense anyway.
Tested manually.
> frost-client: don't allow overwriting contacts

- participant/src/cli.rs
- participant/src/comms.rs
- participant/src/comms/cli.rs
- participant/src/comms/http.rs
- participant/src/comms/socket.rs
- participant/src/round2.rs
- participant/src/tests/round2.rs
- participant/tests/integration_tests.rs
Closes #476 
I also did a small cleanup of passing `SendSigningPackageArgs` around instead of just `SigningPackage` since the former will actually have all the information the user needs to confirm what they're signing.
We don't address it exactly as suggested; rationale:
> Since the tool is not aware of the protocol using it it's not possible to do the verification itself. However, it's important to show the user what they're signing and ask them if they really want to sign the message. We introduce that along with a trait method similar to what was suggested. In the context of Zcash, this will be amended later to show the transaction plan of the transaction being signed. At that point we will likely introduce some Content-Type data that will allow the user to understand what kind of …
> frost-client: add message confirmation step to Comms trait

- frost-client/src/args.rs
- frost-client/src/init.rs
Related to #481; does not fully address it, but we probably still want to address it later.
Rationale: 
> We agree this is important but we will need to think carefully about the design considering interoperability with other applications. We'll schedule this work for later and in the meantime will add warnings about the issue in the documentation.
> frost-client: add warning about unencrypted contents

- Cargo.lock
- coordinator/src/args.rs
- coordinator/src/comms/http.rs
- dkg/src/args.rs
- dkg/src/cli.rs
- dkg/src/comms.rs
- dkg/src/comms/cli.rs
- dkg/src/comms/http.rs
- frost-client/Cargo.toml
- frost-client/src/config.rs
- frost-client/src/contact.rs
- frost-client/src/coordinator.rs
- frost-client/src/dkg.rs
- frost-client/src/init.rs
- frost-client/src/session.rs
- frostd/src/functions.rs
- frostd/src/state.rs
- frostd/src/types.rs
- frostd/src/user.rs
- frostd/tests/integration_tests.rs
- participant/src/args.rs
- participant/src/comms/http.rs
This was done in preparation for #477. It does part of the last item in https://github.com/ZcashFoundation/frost-zcash-demo/issues/313
> use PublicKey type throughout the workspace

- coordinator/src/cli.rs
- coordinator/src/comms.rs
- coordinator/src/comms/http.rs
- coordinator/src/step_1.rs
- dkg/src/cli.rs
- dkg/src/comms.rs
- dkg/src/comms/http.rs
- frostd/src/functions.rs
- frostd/src/types.rs
- frostd/tests/integration_tests.rs
Based on #485
Closes #480.
The issue is not addressed directly as suggested; rationale:
> FROST is not a robust protocol, meaning participants can always prevent a signing sessions from succeeding. For this reason, we don't actively try to prevent participants from being able to abort sessions; they can do that in a myriad of different ways like sending a invalid encrypted message. That being said, we did add a message limit check on the server to mitigate memory exhaustion (since otherwise the length would only be checked when someone receives and decrypts a message). We also added session cleanup in case of error for coordinator and DKG starter, to avoid having aborted sessions lingering in case of error during the protocol.
> frostd, dkg, coordinator: check msg size; cleanup on error

- frost-client/src/args.rs
- frost-client/src/trusted_dealer.rs
Closes #472 
We do not address the finding directly. Rationale:
As it stands, we believe the suggested check wouldn't be meaningful. Only after receiving the config files would the participants need to verify the commitments, which happens outside of the tool; additionally, that requires the commitments which are not stored in the config file. We believe it also does not make sense to include the check for reference because that requires a broadcast channel which is complicated to setup. We decided to instead add warnings on the command line help and in the source code.
> frost-client: add trusted-dealer warnings

- Cargo.lock
- Cargo.toml
- dkg/Cargo.toml
- dkg/src/args.rs
- dkg/src/cli.rs
- frost-client/Cargo.toml
- frost-client/src/config.rs
- frost-client/src/contact.rs
- frost-client/src/dkg.rs
- frost-client/src/trusted_dealer.rs
- frostd/Cargo.toml
- frostd/src/types.rs
- participant/Cargo.toml
- participant/src/args.rs
- participant/src/cli.rs
(Possibly?) Closes #471 
Depends on #469 
I don't think this fully addresses the issue. I believe to have a good level of assurance of secrets being deleted we might need to improve frost_core zeroization handling. I created https://github.com/ZcashFoundation/frost/issues/877 to track it.
> all: best-effort at zeroization of secrets

- Cargo.toml
- coordinator/src/args.rs
- coordinator/src/comms/http.rs
- dkg/src/args.rs
- dkg/src/comms/http.rs
- frost-client/src/config.rs
- frost-client/src/init.rs
- frost-client/src/lib.rs
- frost-client/src/session.rs
- frostd/Cargo.toml
- frostd/src/cipher.rs
- frostd/src/lib.rs
- frostd/tests/integration_tests.rs
- participant/src/args.rs
- participant/src/comms/http.rs
Based on #495
Closes #477 
I wanted to put Cipher in frost-client, so that frost-client also works as a library that applications can import.
However, that introduces a circular import because e.g. coordinator would import frost-client which imports coordinator. To break the cycle I put it into frostd for now. After https://github.com/ZcashFoundation/frost-zcash-demo/issues/380 we can move it back to frost-client.
> all: refactor encryption code into separate module

- dkg/src/comms/http.rs
Closes #487 
Staring at the echo broadcast protocol, I concluded its second part degenerates into nothing if there are only two participants. So just skip it in that case.
> frost-client: fix DKG with 2 participants

- frost-client/src/cli/coordinator.rs
- frost-client/src/cli/dkg.rs
- frost-client/src/cli/participant.rs
- frost-client/src/cli/session.rs
- frost-client/src/coordinator/comms/cli.rs
- frost-client/src/coordinator/input.rs
- frost-client/src/coordinator/main.rs
- frost-client/src/coordinator/tests/common/mod.rs
- frost-client/src/coordinator/tests/steps.rs
- frost-client/src/participant/comms/socket.rs
- frost-client/src/participant/input.rs
- frost-client/src/participant/main.rs
- frostd/tests/integration_tests.rs
- zcash-sign/src/main.rs
- zcash-sign/src/sign.rs
We started getting clippy warnings for `uninlined_format_args`. This fixes those warnings.
> Fix uninlined_format_args clippy rule
