ZcashFoundation/frost-tools

Cargo.lock
Cargo.toml
README.md
src/inputs.rs
src/main.rs
src/tests/inputs_tests.rs
src/tests/integration_test.rs
src/tests/output_tests.rs
src/trusted_dealer_keygen.rs

Implement the split() function in the demo

Add split 362

---

participant/src/cli.rs
participant/src/lib.rs
participant/src/main.rs
participant/src/tests/cli.rs

Add Participant identifier input for Participant CLI

---

Cargo.lock
participant/Cargo.toml
participant/src/lib.rs
participant/src/tests/cli.rs

Add public key to Participant project

---

participant/src/lib.rs
participant/src/tests/cli.rs
participant/src/tests/lib.rs

Add group public key to participant project

---

participant/src/lib.rs
participant/src/tests/cli.rs
participant/src/tests/lib.rs

Add secret share input for participant project

---

Cargo.lock
participant/Cargo.toml
participant/src/cli.rs
participant/src/lib.rs
participant/src/tests/cli.rs
participant/src/tests/lib.rs
trusted-dealer/Cargo.toml
trusted-dealer/src/output.rs
trusted-dealer/src/tests/integration_test.rs
trusted-dealer/src/tests/output_tests.rs

Add vss commitment to participant demo and generate key package

---

Cargo.lock
participant/Cargo.toml
participant/src/cli.rs
participant/src/lib.rs
participant/src/tests/cli.rs
participant/src/tests/lib.rs

Generate nonces and commitments in participant demo

---

coordinator/src/lib.rs
coordinator/src/step_1.rs
coordinator/src/tests/steps.rs

Add unit tests to coordinator demo

---

Cargo.lock
coordinator/tests/integration_tests.rs
participant/src/round1.rs
participant/src/tests/round1.rs
participant/src/tests/round2.rs
participant/tests/integration_tests.rs
trusted-dealer/Cargo.toml
trusted-dealer/src/tests/output_tests.rs

Fix serde tests across the projects

---

dkg/src/tests/inputs.rs
participant/src/cli.rs
participant/src/main.rs
participant/src/round1.rs
participant/src/round2.rs
participant/src/tests.rs
participant/src/tests/cli.rs
tests/tests/integration_tests.rs

This closes #56.
This depends on #76.

Add signature verification step to participant demo

---

Cargo.lock
coordinator/src/args.rs
coordinator/src/cli.rs
coordinator/src/comms/socket.rs
coordinator/src/main.rs
coordinator/src/step_1.rs
coordinator/src/step_2.rs
coordinator/src/step_3.rs
participant/src/cli.rs
participant/src/main.rs
tests/tests/integration_tests.rs
trusted-dealer/Cargo.toml
trusted-dealer/src/args.rs
trusted-dealer/src/cli.rs
trusted-dealer/src/inputs.rs
trusted-dealer/src/lib.rs
trusted-dealer/src/main.rs

change coordinator and participant to allow them to be non-interactive

---

server/src/functions.rs
server/src/state.rs
server/src/types.rs
server/tests/integration_tests.rs

Phase 2: server: change create_new_session to not require specific signers

---

.github/workflows/main.yml
Cargo.lock
coordinator/src/args.rs
coordinator/src/cli.rs
coordinator/src/comms/socket.rs
coordinator/src/step_1.rs
coordinator/src/step_2.rs
coordinator/src/step_3.rs
coordinator/src/tests.rs
coordinator/src/tests/common/mod.rs
coordinator/src/tests/steps.rs
participant/src/args.rs
participant/src/comms/socket.rs
participant/src/round1.rs
tests/tests/integration_tests.rs

* The coordinator unit tests weren't being run. This turns them back on and fixes the error.
* A helper file for the tests was added to make it easier to see the values
* Some clean up was done that was leftover from #131

Fix coordinator units tests

---

Cargo.lock
coordinator/Cargo.toml
coordinator/src/comms/http.rs
participant/src/comms/http.rs
server/Cargo.toml
server/src/functions.rs
server/src/state.rs
server/src/types.rs
server/tests/integration_tests.rs

server: make it ciphersuite-generic

---

Cargo.lock
coordinator/Cargo.toml
coordinator/src/comms/cli.rs
coordinator/src/step_1.rs
coordinator/src/step_3.rs
coordinator/src/tests/steps.rs
dkg/Cargo.toml
dkg/src/inputs.rs
participant/Cargo.toml
participant/src/comms/cli.rs
participant/src/tests/round1.rs
participant/src/tests/round2.rs
server/Cargo.toml
server/src/types.rs
tests/Cargo.toml
trusted-dealer/Cargo.toml
trusted-dealer/src/trusted_dealer_keygen.rs

update to frost 2.0.0-rc.0

---

supply-chain/audits.toml
supply-chain/config.toml
supply-chain/imports.lock

Adds cargo vet setup using the same trsuted imports as Zebra

Add cargo vet

---

Cargo.lock
coordinator/Cargo.toml
dkg/Cargo.toml
dkg/src/comms.rs
dkg/src/comms/http.rs
frost-client/Cargo.toml
frostd/Cargo.toml
frostd/src/lib.rs
frostd/tests/integration_tests.rs
participant/Cargo.toml

frost-client: add broadcast channel to DKG

---

frost-client/src/dkg.rs

Forgot to do the fix from https://github.com/ZcashFoundation/frost-zcash-demo/pull/450 in the dkg tool too

dkg: fix port handling

---

Cargo.lock
Cargo.toml
coordinator/Cargo.toml
dkg/Cargo.toml
frost-client/Cargo.toml
frostd/Cargo.toml
frostd/src/types.rs
participant/Cargo.toml
participant/src/round1.rs
participant/src/tests/round1.rs

Based on #468 
Closes #470 
I went ahead and also removed the OpenSSL dependency; it seems a good idea not to depend on it.
I also removed a couple of unused dependencies.

all: update and clean up dependencies

---

frost-client/src/contact.rs
frostd/src/functions.rs
frostd/src/lib.rs
frostd/tests/integration_tests.rs

frostd: validate sender and recipient in send and receive
